config/routes.rb
Rails.application.routes.draw do
  resources :credits, only: [:index, :new, :show, :create, :destroy] do
    resources :transactions, only: [:index, :new, :show, :create, :destroy]
  end
  root to: 'credits#index'
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  validates :apr, presence: true, numericality: {less_than: 1.0, greater_than: 0.0}
  validates :line_max, presence: true, numericality: {greater_than:0.0}
  validates :name, presence: true

  has_many :transactions

  def interest_total
    interests = []
    self.transactions.each_cons(2) do |line_item, next_line_item|
      duration = next_line_item.day.to_i - line_item.day
      interests << segment_total(segment_balance(line_item), self.apr, duration)
    end
    interests << last_transaction(self.transactions.last, self.current_balance)
    interests.reduce(:+).to_f
  end

  def current_balance
    loan_amounts = []
    self.transactions.each do |credit|
      deposit_or_withdraw_amount(credit, loan_amounts)
    end
    loan_amounts.reduce(:+)
  end

  def grand_totals
    if self.transactions.count > 0
      self.interest_total + self.current_balance
    else
      "00.00".to_f
    end
  end

  private
  def segment_total(amount, apr, duration)
    (amount * apr / 365 * (duration)).round(2)
  end

  def deposit_or_withdraw_amount(transaction, array)
    if transaction.withdrawal
      array << transaction.amount
    else
      array << -transaction.amount.to_f
    end
  end

  def last_transaction(last_transaction, balance)
    duration = 30 - last_transaction.day
    segment_total(segment_balance(last_transaction), self.apr, duration)
  end

  def segment_balance(segment)
    if segment.day == 0
      loan_amount = segment.amount
    else
      loan_amount = self.current_balance
    end
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :credit

  validates :credit, presence: true
  validates :amount, presence: true
  validates :day, presence: true, numericality: {less_than: 31}
#  validate :within_credit_line_max, if: Proc.new{|a| a.withdrawal}

#  def within_credit_line_max
#    line = self.credit
#    if self.amount > line.line_max
#      self.errors[:transaction] << "exceeds credit line"
#    end
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
    @credits = Credit.all
  end

  def new
    @credit = Credit.new()
  end

  def create
    @credit = Credit.new(credit_params)
    if @credit.save
      redirect_to @credit
    end
  end

  def show
    @credit = Credit.find(params[:id])
    @transactions = @credit.transactions
  end

  private
  def credit_params
    params.require(:credit).permit(:name, :apr, :line_max)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new()
  end

  def create
    @credit = Credit.find(params[:credit_id])
    @transaction = @credit.transactions.create(transaction_params)
    redirect_to credit_path(@credit.id)
  end

  private
  def transaction_params
    params.require(:transaction).permit(:amount, :day, :withdrawal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/create.html.haml
%h1 Credits#create
%p Find me in app/views/credits/create.html.haml

app/views/credits/destroy.html.haml
%h1 Credits#destroy
%p Find me in app/views/credits/destroy.html.haml

app/views/credits/index.html.haml
%h1
  All Lines of Credit
%hr
%table
  %tr
    %th
      Name
    %th
      APR
    %th
      Credit Max
    %th
      Due at End of Month
  -@credits.each do |credit|
    %tr
      %td
        = link_to "#{credit.name}", credit_path(credit)
      %td
        #{credit.apr * 100}%
      %td
        $#{sprintf('%.2f', credit.line_max)}
      %td
        $#{sprintf('%.2f', credit.grand_totals)}

%br
%p
  = link_to 'Add a New Line of Credit', new_credit_path

app/views/credits/new.html.haml
=simple_form_for @credit, url: credits_path do |f|
  %p
    =f.input :name, label: 'Name'
  %p
    =f.input :apr, label: 'APR', placeholder: '0.15', hint: ' Any value 0.00 to  1.0'
  %p
    =f.input :line_max, label: 'Line of Credit Maximum', placeholder: '1000.00'
  %p
    =f.submit 'Apply'

app/views/credits/show.html.haml
%h1
  #{@credit.name}'s Line of Credit
%p
  %span
    %strong
      APR
    #{@credit.apr * 100}%
%p
  %strong
    Maximum Line of Credit
  $#{sprintf('%.2f', @credit.line_max)}
=link_to 'Return to Credit Dashboard', credits_path
%hr
%p
  %strong
    Transactions
  - if @transactions.exists?
    %table
      %tr
        %th
          Day of the Month
        %th
          Transaction Type
        %th
          Amount
      -@transactions.each do |transaction|
        %tr
          %td
            =transaction.day
          %td
            - if transaction.withdrawal
              Withdrawal
            - else
              Deposit
          %td
            $#{sprintf('%.2f', transaction.amount)}
  - else
    %p
      None Yet
%p
  %button
    =link_to 'add transactions', new_credit_transaction_path(@credit.id)
- if @transactions.exists?
  %p
    %strong
      Grand Total Due At End of Month
    %br
    $#{sprintf('%.2f', @credit.grand_totals)}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LineOfCredit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/transactions/create.html.haml
%h1 Transactions#create
%p Find me in app/views/transactions/create.html.haml

app/views/transactions/destroy.html.haml
%h1 Transactions#destroy
%p Find me in app/views/transactions/destroy.html.haml

app/views/transactions/new.html.haml
=simple_form_for @transaction, url: credit_transactions_path do |f|
  %p
    =f.input :amount, label: 'Amount'
  %p
    =f.input :day, label: 'day', placeholder:'10'
  %p
    =f.input :withdrawal, label: 'Withdrawal', as: :boolean, boolean_style: :inline
  %p
    =f.submit

app/views/transactions/show.html.haml
%h1 Transactions#show
%p Find me in app/views/transactions/show.html.haml